blog/urls.py
from django.urls import path
from blog.views import \
    (home_view
, DetailClass,
     ArticleCateGoryList,
     CateGoryList,
     AuthorList,
    ArticlePreview,
    Search,
     like,
    TagPostList,
    about_us,
    TagList,
    AllPost,
     )

app_name = 'blog'
urlpatterns = [
    path('', home_view, name='home'),

    path('article/<slug>-<id>', DetailClass.as_view(), name='detail'),
    path('preview/<slug>-<pk>', ArticlePreview.as_view(), name='preview'),
    path('category/<slug>', ArticleCateGoryList.as_view(), name='article-category'),
    path('category/<slug>/page/<int:page>', ArticleCateGoryList.as_view(), name='article-category'),
    path('search', Search.as_view(), name='search'),
    path('search/page/<int:page>', Search.as_view(), name='search'),
    path('category/', CateGoryList.as_view(), name='category'),
    path('category/page/<int:page>', CateGoryList.as_view(), name='category'),
    path('author/<slug:username>', AuthorList.as_view(), name='author'),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name='author'),
    path('hashtag/<tag_slug>/<tag_id>/<title>', TagPostList.as_view(), name='hashtag'),
    path('hashtag/<tag_slug>/<tag_id>/page/<int:page>/<title>', TagPostList.as_view(), name='hashtag'),
    path('hashtag/', TagList.as_view(), name='hashtag-list'),
    path('like/<id>', like, name='like'),
    path('about_us', about_us, name='about-us'),
    path('articles', AllPost.as_view(), name='all-article'),

]

contact_us/urls.py
from django.urls import path


from .views import Contact, success_send_message_contact
app_name = 'contact'

urlpatterns = [
    path('', Contact.as_view(), name='contact-us'),
    path('success_contact', success_send_message_contact, name='success-contact'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from account.views import login_users, logout_user
from .views import header_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('login/', login_users, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('header/', header_view, name='header'),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from email.policy import default

from django.db import models
from django.utils import timezone
from extensions.utils import django_jalali_converter
from django.utils.html import format_html
from account.models import User
from django.shortcuts import reverse
from django.contrib.contenttypes.fields import GenericRelation

from comment.models import Comment


class CatGoryManager(models.Manager):
    def category_status(self, slug):
        return self.filter(status=True, slug=slug)

    def category_active(self):
        return self.filter(status=True)




class CateGory(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='عنوان دسته بندی در url')
    parent = models.ForeignKey('self', default=None, blank=True, null=True, on_delete=models.CASCADE, related_name='children', verbose_name='والد')
    status = models.BooleanField(default=True, verbose_name='این دسته بندی  نمایش داده شوند؟')
    position = models.IntegerField(verbose_name='پوزیشن')
    image = models.ImageField(upload_to='category', default='category/defualt.jpg', verbose_name='تصویر دسته بندی')


    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        return self.title

    objects = CatGoryManager()


class IPAddress(models.Model):
    ip = models.GenericIPAddressField(verbose_name='آی پی آدرس')

    class Meta:
        verbose_name = 'ی پی آدرس کاربران'
        verbose_name_plural = 'آی پی آدرس کاربران'

    def __str__(self):
        return self.ip


class PostManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class Post(models.Model):
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, related_name='articles', verbose_name='نویسنده')
    STATUS_CHOICES = (
        ('d', ' پیش نویس'),
        ('p', 'منتشر شده'),
        ('i', 'در حال بررسی'),
        ('b', 'برگشت داده شده'),
    )
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='عنوان در url')
    description = models.TextField(verbose_name='توضیحات')
    image = models.ImageField(upload_to='image_post', verbose_name='تصویر')
    published_time = models.DateTimeField(default=timezone.now(), verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')
    updated = models.DateTimeField(auto_now=True, verbose_name='اخرین به روز رسانی')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')
    category = models.ManyToManyField(CateGory, verbose_name='دسته بندی', related_name='post_category')
    number_post = models.IntegerField(unique=True, blank=True, null=True, verbose_name='شماره پست')
    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through='PostHit', blank=True, null=True, related_name='hits')
    like_user = models.ManyToManyField(User, blank=True, null=True, verbose_name='پسندها')



    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'
        ordering = ['-published_time']


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('account:home')

    def j_published(self):
        return django_jalali_converter(self.published_time)
    j_published.short_description = 'زمان انتشار'


    def image_tag(self):
        return format_html("<img height=100px width=110px style='border-radius: 5px;'  src='{}'>".format(self.image.url))
    image_tag.short_description = 'تصویر'
    objects = PostManager()

    def category_to_str(self):
        return ', '.join([category.title for category in self.category.category_active()])
    category_to_str.short_description = 'دسته بندی'



class PostHit(models.Model):
    post = models.ForeignKey(Post, verbose_name='مقاله', on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, verbose_name='آی پی آدرس', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')

class Slider(models.Model):
    title = models.CharField(max_length=200, default='slider', verbose_name='عنوان')
    posts_slider = models.ManyToManyField(Post, blank=True, null=True, related_name='slider_p', verbose_name='پست های اسلایدر')
    active = models.BooleanField(default=False, verbose_name='اسلایدر فعال')

    class Meta:
        verbose_name = 'اسلایدر'
        verbose_name_plural = 'اسلایدر'

    def __str__(self):
        return self.title



class Hashtag(models.Model):
    post = models.ManyToManyField(Post, verbose_name='پست', related_name='tag_post')
    title = models.CharField(max_length=200, verbose_name='عنوان', default='خبر')
    slug = models.SlugField(max_length=100, default='news', unique=True, verbose_name='عنوان در url')
    hits = models.ManyToManyField(IPAddress, through='TagHit', blank=True, null=True, related_name='tag_hit')


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'هشتگ'
        verbose_name_plural = 'هشتگ ها'


class TagHit(models.Model):
    post = models.ForeignKey(Hashtag, verbose_name='برچسب', on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, verbose_name='آی پی آدرس', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')

blog/views.py
from account.models import User
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Slider, Hashtag
import itertools
from .models import CateGory
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from account.mixins import AuthorAccessArticleMixin
from django.db.models import Q
from django.db.models import Count
from comment.models.comments import Comment
import datetime

def my_grouper(n, iterable):
    args = [iter(iterable)] * n
    return ([e for e in t if e is not None] for t in itertools.zip_longest(*args))

def about_us(request):
    return render(request, 'blog/about_us.html', {'title' : 'درباره ما'})
   
def home_view(request):
    admin = User.objects.get(is_superuser=True)
    posts = Post.objects.published()[:4]
    all_post = Post.objects.published()
    my_grouper_post = my_grouper(2, posts)
    sliders = Slider.objects.filter(active=True)[:1]
    purpal_news = Post.objects.order_by('-like_user').distinct()[:6]
    hot_news = Post.objects.published().annotate(count=Count('hits', filter=Q(comments__content_type_id=7))).order_by('-count').distinct()[:6]
    comments = Comment.objects.all().distinct()[:6]
    best_news = Post.objects.published().annotate(count=Count('hits')).order_by('-count').distinct()[:4]
    last_week = datetime.date.today() - datetime.timedelta(days=7)
    best_news_last_week = Post.objects.filter(published_time__range=[last_week, datetime.date.today()]).order_by('-hits', '-published_time').distinct()[:4]
    best_tag = Hashtag.objects.all().annotate(count=Count('post')).order_by('-count').distinct()[:10]
    count_like = 0
    for posts in all_post.all():
        for likes in posts.like_user.all():
            count_like += 1
    context = {'posts': my_grouper_post, 'all_post': all_post,
               'title': 'خانه', 'sliders': sliders, 'count_like' : count_like,
               'purpal_news': purpal_news, 'hot_news': hot_news, 'comments': comments, 'best_news': best_news,
               'best_news_last_week' :best_news_last_week, 'best_tag': best_tag, 'admin' : admin
 }
    return render(request, 'blog/index.html', context)




class DetailClass(DetailView):
    template_name = 'blog/single-post.html'  #or change name template to article_detail.html

    def get_object(self, queryset=None):
        global post
        id = self.kwargs.get('id')
        slug = self.kwargs.get('slug')
        post = get_object_or_404(Post.objects.published(), slug=slug, id=id)
        ip = self.request.user.ip_address
        if ip not in post.hits.all():
            post.hits.add(ip)
            post.save()
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['new_post'] = Post.objects.published()[1:6]
        context['end_news'] = Post.objects.published().first()
        context['related_post'] = Post.objects.get_queryset().filter(category__post_category=post).distinct()[:2]
        return context



class ArticlePreview(AuthorAccessArticleMixin, DetailView):
    template_name = 'blog/single-post.html'
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        slug = self.kwargs.get('slug')
        return get_object_or_404(Post.objects, slug=slug, pk=pk)

class ArticleCateGoryList(ListView):
    paginate_by = 2
    template_name = 'blog/article_category.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(CateGory.objects.category_status(slug))
        return category.post_category.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        end_news1 = Post.objects.published()[:1]
        end_news2 = Post.objects.published()[1:3]
        context['category'] = category
        context['end_news1'] = end_news1
        context['end_news2'] = end_news2
        return context




class Search(ListView):
    paginate_by = 10
    template_name = 'blog/all_post_search.html'

    def get_queryset(self):
        global q, posts
        q = self.request.GET.get('q')
        return Post.objects.filter(Q(title__icontains=q)|Q(description__icontains=q))


    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        all_post = Post.objects.published()
        context['q'] = q
        context['all_post'] = all_post
        return context

class AllPost(ListView):
    paginate_by = 10
    template_name = 'blog/all_post_search.html'
    model = Post
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        all_post = Post.objects.published().distinct()
        new_post = Post.objects.order_by('-id').distinct()
        purpal_news = Post.objects.order_by('-like_user').distinct()
        max_vist_news = Post.objects.published().annotate(
        count=Count('hits')).order_by('-count').distinct()
        context['all_post'] = all_post
        context['new_post'] = new_post
        context['purpal_news'] = purpal_news
        context['max_vist_news'] = max_vist_news
        context['request'] = self.request
        return context

class CateGoryList(ListView):
    paginate_by = 5
    template_name = 'blog/category.html'
    def get_queryset(self):
        category = CateGory.objects.category_active()
        return category

class AuthorList(ListView):
    paginate_by = 2
    template_name = 'blog/author_page.html'
    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        end_news1 = Post.objects.published()[:1]
        end_news2 = Post.objects.published()[1:3]
        context['end_news1'] = end_news1
        context['end_news2'] = end_news2
        context['author'] = author
        return context


class TagPostList(ListView):
    paginate_by = 2
    template_name = 'blog/tag_post_list.html'
    def get_queryset(self):
        global hashtag
        tag_id = self.kwargs.get('tag_id')
        tag_slug = self.kwargs.get('tag_slug')
        title = self.kwargs.get('title')
        hashtag = get_object_or_404(Hashtag, slug=tag_slug, id=tag_id, title=title)
        ip = self.request.user.ip_address
        if ip not in hashtag.hits.all():
            hashtag.hits.add(ip)
            hashtag.save()
        return hashtag.post.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        end_news1 = Post.objects.published()[:1]
        end_news2 = Post.objects.published()[1:3]
        context['end_news1'] = end_news1
        context['end_news2'] = end_news2
        context['hashtag'] = hashtag
        return context

def like(request, id):
    user = request.user
    if not user.is_authenticated:
        return redirect('login_user')
    post = Post.objects.get(id=id)
    if user in post.like_user.all():
        post.like_user.remove(user)
    else:
        post.like_user.add(user)
    return redirect('blog:detail', post.slug, post.id)

class TagList(ListView):
    template_name = 'blog/tag_list.html'
    model = Hashtag

    def get_context_data(self):
        context = super().get_context_data()
        hashtags = Hashtag.objects.all()
        context['hashtags_group'] = my_grouper(10, hashtags)
        return context

templates/blog/about_us.html
{% extends 'blog/../shared/base.html' %}
{% load static %}
{% load render_partial %}
{% load base_tags %}
{% load comment_tags %}
{%block title%}
{{ title }}
{% endblock %}
{% block header %}
{% render_partial 'header' %}
{% endblock %}
{% block main %}

	<section class="page">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ol class="breadcrumb d-flex justify-content-center">
						<li><a href="{% url 'blog:home' %}">خانه</a></li>
						<li class="active">درباره ما</li>
					</ol>
					<h1 class="page-title text-center">درباره ما</h1>
					<div class="line thin"></div>
					<div class="page-description">
						<p>
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
						</p>

						<p>
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوملورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوم
						</p>

						<p>
							لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوملورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی
							نامفهوم لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
						</p>
						<div class="question">
							سوالی دارید ؟ <a href="{% url 'contact:contact-us' %}" class="btn btn-primary">تماس با ما</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


{% endblock main %}
{% block footer %}
{% footer_view %}
{% endblock %}

templates/blog/article_category.html
{% extends 'blog/../shared/category_base.html'%}
{%block title%}
دسته بندی | {{category.title}}
{% endblock %}
{% block cat_title %}
<div class="col-md-12">
   <ol class="breadcrumb">
      <li><a href="#">خانه</a></li>
      <li><a href="{% url 'blog:category' %}">دسته بندی</a></li>
      <li class="active">{{ category.title }}</li>
   </ol>
   <h1 class="page-title mt-3">دسته بندی : {{ category.title }}</h1>
   <p class="page-subtitle text-large mb-4">نمایش پست ها با دسته بندی <i>{{ category.title }}</i></p>
</div>
{% endblock %}
{% block article %}
<div class="line mt-1"></div>
<div class="row">
{% for post in object_list %}
<article class="col-md-12 article-list">
   <div class="inner">
      <figure>
         <a href="{% url 'blog:detail' post.slug post.id %}">
         <img src="{{ post.image.url }}">
         </a>
      </figure>
      <div class="details">
         <div class="detail text-right d-flex">
            <div class="category">
               {% for cat in post.category_published.all %}
               <a href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
               {% endfor %}
            </div>
            <div class="time"><i class="fa fa-clock"></i> {{post.j_published}}</div>
         </div>
         {% if post.is_special %}
         <span class="badge badge-danger" style="font-size: 10px;">ویژه</span>
         {% endif %}
         <h1 class="pt-0"><a href="{% url 'blog:detail' post.slug post.id %}">{{ post.title|truncatewords:20  }}</a></h1>
         <p>{{ post.description|striptags|truncatewords:40|safe }}
         </p>
         <footer class="mt-2">
            <a href="#" class="love">
               <i class="ion-android-favorite-outline"></i>
               <div>145</div>
            </a>
            <a class="btn btn-primary more" href="{% url 'blog:detail' post.slug post.id%}">
               <div>بیشتر</div>
               <div><i class="ion-ios-arrow-thin-left"></i></div>
            </a>
         </footer>
      </div>
   </div>
</article>
{% endfor %}
{% endblock %}
{% block paginator %}
<div class="col-md-12 text-center d-flex justify-content-center">
   <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="prev"><a href="{% url 'blog:article-category' category.slug page_obj.previous_page_number %}"><i class="ion-ios-arrow-right"></i></a></li>
      {% endif %}
      {% for page in page_obj.paginator.page_range  %}
      {% if page == page_obj.number %}
      <li class="active"><a href="{% url 'blog:article-category' category.slug page %}">{{ page }}</a></li>
      {% else %}
      <li><a href="{% url 'blog:article-category' category.slug page %}">{{ page }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="next"><a href="{% url 'blog:article-category' category.slug page_obj.next_page_number %}"><i class="ion-ios-arrow-left"></i></a></li>
      {% endif %}
   </ul>
</div>
{% endblock %}

templates/blog/author_page.html
{% extends 'blog/../shared/category_base.html'%}
{%block title%}
نویسنده | {{ author.username }}
{% endblock %}
{% block cat_title %}
<div class="col-md-12">
   <ol class="breadcrumb">
      <li><a href="#">خانه</a></li>
      <li><a href="#">نویسنده </a></li>
      <li class="active">{{ author.username }}</li>
   </ol>
   <h1 class="page-title mt-3"> نویسنده : {{ author.username }}</h1>
   <p class="page-subtitle text-large mb-4">نمایش پست ها با نویسنده :<i>{{ author.username }}</i></p>
</div>
{% endblock %}
{% block article %}
<div class="line mt-1"></div>
<div class="row">
{% for post in object_list %}
<article class="col-md-12 article-list">
   <div class="inner">
      <figure>
         <a href="{% url 'blog:detail' post.slug post.id %}">
         <img src="{{ post.image.url }}">
         </a>
      </figure>
      <div class="details">
         <div class="detail text-right d-flex">
            <div class="category">
               {% for cat in post.category.all %}
               <a href="{% url 'blog:article-category' cat.slug %}">{{cat.title}}</a>
               {% endfor %}
            </div>
            {% if post.is_special %}
            <span class="badge badge-danger" style="font-size: 10px;">ویژه</span>
            {% endif %}
            <div class="time"><i class="fa fa-clock"></i> {{post.j_published}}</div>
         </div>
         <h1 class="pt-0"><a href="{% url 'blog:detail' post.slug post.id %}">{{ post.title|truncatewords:20  }}</a></h1>
         <p style="">{{ post.description|striptags|truncatewords:40|safe }}</p>
         </p>
         <footer class="mt-2">
            <a href="#" class="love">
               <i class="ion-android-favorite-outline"></i>
               <div>145</div>
            </a>
            <a class="btn btn-primary more" href="{% url 'blog:detail' post.slug post.id%}">
               <div>بیشتر</div>
               <div><i class="ion-ios-arrow-thin-left"></i></div>
            </a>
         </footer>
      </div>
   </div>
</article>
{% endfor %}
{% endblock %}
{% block paginator %}
<div class="col-md-12 text-center d-flex justify-content-center">
   <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="prev"><a href="{% url 'blog:author' author.username page_obj.previous_page_number %}"><i class="ion-ios-arrow-right"></i></a></li>
      {% endif %}
      {% for page in page_obj.paginator.page_range  %}
      {% if page == page_obj.number %}
      <li class="active"><a href="{% url 'blog:author' author.username page %}">{{ page }}</a></li>
      {% else %}
      <li><a href="{% url 'blog:author' author.username page %}">{{ page }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="next"><a href="{% url 'blog:author' author.username page_obj.next_page_number %}"><i class="ion-ios-arrow-left"></i></a></li>
      {% endif %}
   </ul>
</div>
{% endblock %}

templates/blog/tag_list.html
{% extends 'blog/../shared/base.html' %}
{% load static %}
{% load render_partial %}
{% load base_tags %}
{% load comment_tags %}
{%block title%}
لیست هشتگ ها
{% endblock %}
{% block header %}
{% render_partial 'header' %}
{% endblock %}
{% block main %}

	<section class="page">
    <h1 style="text-align: center;margin:30px;">لیست برچسب ها</h1>
        <hr>
    	<div class="container">
			<div class="row" style="display:flex">
        {% for hashtag in hashtags_group %}
            <div class="column" style="float: left; width:25%;flex:25%;">
							<h1 class="title-col">برچسب های برتر</h1>
							<div class="body-col">
								<ol class="tags-list">
                                    {% for tag in hashtag %}
									<li><a href="{% url 'blog:hashtag' tag.slug tag.id tag.title%}">{{ tag.title }}</a></li>
                                        {% endfor %}
								</ol>
							</div>
            </div>
        {% endfor %}
                            </div>
        </div>
    </section>

{% endblock main %}
{% block footer %}
{% footer_view %}
{% endblock %}

templates/blog/tag_post_list.html
{% extends 'blog/../shared/category_base.html'%}
{%block title%}
برچسب | {{ hashtag.title }}
{% endblock %}
{% block cat_title %}
<div class="col-md-12">
   <ol class="breadcrumb">
      <li><a href="{% url 'blog:home' %}">خانه</a></li>
      <li><a href="#">{{ hashtag.title }} </a></li>
   </ol>
   <p class="page-subtitle text-large mb-4">نمایش پست ها با:<i>{{ hashtag.title }}</i></p>
</div>
{% endblock %}
{% block article %}
<div class="line mt-1"></div>
<div class="row">
{% for post in object_list %}
<article class="col-md-12 article-list">
   <div class="inner">
      <figure>
         <a href="{% url 'blog:detail' post.slug post.id %}">
         <img src="{{ post.image.url }}">
         </a>
      </figure>
      <div class="details">
         <div class="detail text-right d-flex">
            <div class="category">
               {% for cat in post.category.all %}
               <a href="{% url 'blog:article-category' cat.slug %}">{{cat.title}}</a>
               {% endfor %}
            </div>
            {% if post.is_special %}
            <span class="badge badge-danger" style="font-size: 10px;">ویژه</span>
            {% endif %}
            <div class="time"><i class="fa fa-clock"></i> {{post.j_published}}</div>
         </div>
         <h1 class="pt-0"><a href="{% url 'blog:detail' post.slug post.id %}">{{ post.title|truncatewords:20  }}</a></h1>
         <p style="">{{ post.description|striptags|truncatewords:40|safe }}</p>
         </p>
         <footer class="mt-2">
            <a href="#" class="love">
               <i class="ion-android-favorite-outline"></i>
               <div>145</div>
            </a>
            <a class="btn btn-primary more" href="{% url 'blog:detail' post.slug post.id%}">
               <div>بیشتر</div>
               <div><i class="ion-ios-arrow-thin-left"></i></div>
            </a>
         </footer>
      </div>
   </div>
</article>
{% endfor %}
{% endblock %}
{% block paginator %}
<div class="col-md-12 text-center d-flex justify-content-center">
   <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="prev"><a href="{% url 'blog:hashtag' hashtag.slug hashtag.id page_obj.previous_page_number %}"><i class="ion-ios-arrow-right"></i></a></li>
      {% endif %}
      {% for page in page_obj.paginator.page_range  %}
      {% if page == page_obj.number %}
      <li class="active"><a href="{% url 'blog:hashtag' hashtag.slug hashtag.id page %}">{{ page }}</a></li>
      {% else %}
      <li><a href="{% url 'blog:hashtag' hashtag.slug hashtag.id page %}">{{ page }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="next"><a href="{% url 'blog:hashtag' hashtag.slug hashtag.id page_obj.next_page_number %}"><i class="ion-ios-arrow-left"></i></a></li>
      {% endif %}
   </ul>
</div>
{% endblock %}