account/urls.py
from django.urls import path
from .views import (
    ArticleView,
    ArticleCreate,
    ArticleUpdate,
    ArticleDelete,
    Profile,
    signup,
    activate
)
app_name = 'account'

urlpatterns = [
    path('', ArticleView.as_view(), name='home'),
    path('article/create', ArticleCreate.as_view(), name='article-create'),
    path('article/update/<pk>', ArticleUpdate.as_view(), name='article-update'),
    path('profile', Profile.as_view(), name='profile'),
    path('article/delete/<pk>', ArticleDelete.as_view(), name='article-delete'),
    path('signup/', signup, name='signup'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',activate, name='activate'),
]

blog/urls.py
from django.urls import path
from blog.views import \
    (home_view
, DetailClass,
     ArticleCateGoryList,
     CateGoryList,
     AuthorList,
    ArticlePreview,
    Search,
     like,
    TagPostList,
    about_us,
    TagList,
    AllPost,
     )

app_name = 'blog'
urlpatterns = [
    path('', home_view, name='home'),

    path('article/<slug>-<id>', DetailClass.as_view(), name='detail'),
    path('preview/<slug>-<pk>', ArticlePreview.as_view(), name='preview'),
    path('category/<slug>', ArticleCateGoryList.as_view(), name='article-category'),
    path('category/<slug>/page/<int:page>', ArticleCateGoryList.as_view(), name='article-category'),
    path('search', Search.as_view(), name='search'),
    path('search/page/<int:page>', Search.as_view(), name='search'),
    path('category/', CateGoryList.as_view(), name='category'),
    path('category/page/<int:page>', CateGoryList.as_view(), name='category'),
    path('author/<slug:username>', AuthorList.as_view(), name='author'),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name='author'),
    path('hashtag/<tag_slug>/<tag_id>/<title>', TagPostList.as_view(), name='hashtag'),
    path('hashtag/<tag_slug>/<tag_id>/page/<int:page>/<title>', TagPostList.as_view(), name='hashtag'),
    path('hashtag/', TagList.as_view(), name='hashtag-list'),
    path('like/<id>', like, name='like'),
    path('about_us', about_us, name='about-us'),
    path('articles', AllPost.as_view(), name='all-article'),

]

contact_us/urls.py
from django.urls import path


from .views import Contact, success_send_message_contact
app_name = 'contact'

urlpatterns = [
    path('', Contact.as_view(), name='contact-us'),
    path('success_contact', success_send_message_contact, name='success-contact'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from account.views import login_users, logout_user
from .views import header_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('login/', login_users, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('header/', header_view, name='header'),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/shared/Header.html
{% load static %}
<header class="primary">
   <div class="firstbar">
      <div class="container">
         <div class="row">
            <div class="col-lg-3 col-md-12 col-sm-12">
               <div class="brand">
                  <a href="{% url 'blog:home' %}">
                  <img src="{% static 'blog/images/logo.png'%}" alt="Magz Logo">
                  </a>
               </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12">
               <form class="search" autocomplete="off" action="{% url 'blog:search' %}">
                  <div class="form-group">
                     <div class="input-group">
                        <input type="text" name="q" class="form-control"
                           placeholder="جستجوی عبارت مورد نظر ...">
                        <div class="input-group-btn">
                           <button class="btn btn-primary">
                           <a class="ion-search text-white" href="{% url 'blog:search' %}"></a>
                           </button>
                        </div>
                     </div>
                  </div>
                  <div class="help-block mt-2">
                     <div>محبوب ترین ها : </div>
                     <ul>
                         {% for tag in purpal_Tag %}
                        <li><a href="{% url 'blog:hashtag' tag.slug tag.id tag.title %}">{{tag.title}}</a></li>
                        {% endfor %}
                     </ul>
                  </div>
               </form>
            </div>
             {% if not user.is_authenticated  %}
            <div class="col-lg-3 col-md-12 col-sm-12 text-right">
               <ul class="nav-icons">
                  <li>
                     <a href="{% url 'account:signup' %}">
                        <i class="ion-person-add"></i>
                        <div>ثبت نام</div>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'login_user' %}">
                        <i class="ion-person"></i>
                        <div>ورود</div>
                     </a>
                  </li>
               </ul>
            </div>
             {% endif %}
         </div>
      </div>
   </div>
   <!-- Start nav -->
   <nav class="menu">
      <div class="container">
         <div class="brand">
            <a href="{% url 'blog:home' %}">
            <img  src="{% static 'blog/images/logo.png'%}" alt="Magz Logo">
            </a>
         </div>
         <div class="mobile-toggle">
            <a href="#" data-toggle="menu" data-target="#menu-list"><i class="ion-navicon-round"></i></a>
         </div>
         <div class="mobile-toggle">
            <a href="#" data-toggle="sidebar" data-target="#sidebar"><i class="ion-ios-arrow-left"></i></a>
         </div>
         <div id="menu-list">
            <ul class="nav-list">
               <li class="for-tablet nav-title"><a>فهرست</a></li>
               <li class="for-tablet"><a href="{% url 'login_user' %}">ورود</a></li>
               <li class="for-tablet"><a href="register.html">ثبت نام</a></li>
               <li><a href="{% url 'blog:home' %}">خانه</a></li>
               <li class="dropdown magz-dropdown">
                  <a >دسته بندی ها <i class="ion-ios-arrow-left"></i></a>
                  <ul class="dropdown-menu">
                     {% for cat in category %}
                     {% if cat.parent is None %}
                     {% if cat.children.category_active %}
                     <li class="dropdown dropdown">
                        <a href="{% url 'blog:article-category' cat.slug %}">{{ cat.title }} <i class="fa fa-angle-left"></i></a>
                        {% include 'shared/category_loop.html' %}
                     </li>
                     {% else %}
                     <li><a href="{% url 'blog:article-category' cat.slug %}">{{cat.title}}</a></li>
                     {% endif %}
                     {% endif %}
                     {% endfor %}
                  </ul>
               </li>
               <li class="dropdown magz-dropdown magz-dropdown-megamenu">
                  <a href="#">
                     مگامنو <i class="ion-ios-arrow-left"></i>
                  </a>
                  <div class="dropdown-menu megamenu">
                     <div class="megamenu-inner">
                        <div class="row">
                           <div class="col-lg-3">
                              <div class="row">
                                 <div class="col-lg-12">
                                    <h2 class="megamenu-title">ویژه</h2>
                                 </div>
                              </div>
                              <ul class="vertical-menu">
                                  {% for special in post_is_special %}
                                 <li><a href="{% url 'blog:detail' special.slug special.id %}"><i class="ion-ios-circle-outline"></i>{{ special.title|truncatewords:6 }}</a>
                                 </li>
                                  {% endfor %}
                              </ul>
                           </div>
                           <div class="col-lg-9">
                              <div class="row">
                                 <div class="col-lg-12">
                                    <h2 class="megamenu-title">پست های جدید</h2>
                                 </div>
                              </div>
                              <div class="row">
                                  {% for new in new_post %}
                                 <article class="article col-lg-4 mini">
                                    <div class="inner">
                                       <figure>
                                          <a href="{% url 'blog:detail' new.slug new.id %}">
                                          <img src="{{ new.image.url }}" alt="{{ new.title}}">
                                          </a>
                                       </figure>
                                       <div class="padding">
                                          <div class="detail">
                                             <div class="time">{{ new.j_published }}</div>
                                              {% for cat in new.category.all %}
                                                  {% if forloop.first or forloop.last %}
                                             <div class="category"><a href="{% url 'blog:article-category' cat.slug %}">{{ cat.title}}</a>
                                             </div>
                                                  {% endif %}
                                                  {% endfor %}
                                          </div>
                                          <h2><a href="{% url 'blog:detail' new.slug new.id %}">{{ new.title|truncatewords:15  }}</a>
                                          </h2>
                                       </div>
                                    </div>
                                 </article>
                                {% endfor %}
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </li>
                <li><a href="{% url 'blog:about-us' %}">درباره ما</a></li>
                <li><a href="{% url 'contact:contact-us' %}">تماس با ما</a></li>
            {% if request.user.is_authenticated %}
                <li class="dropdown magz-dropdown">
                  <a href="#">منوی کاربری <i
                     class="ion-ios-arrow-left"></i></a>
                  <ul class="dropdown-menu">
                     <li><a href="{% url 'account:home' %}"><i class="icon fa fa-user"></i> پنل کاربری</a></li>
                     <li><a href="#"><i class="icon fa fa-heart"></i> علاقه مندی ها</a></li>
                     <li><a href="#"><i class="icon fa fa-comment"></i> نظرات</a></li>
                     <li><a href=""><i class="icon fa fa-key"></i> تغییر رمز عبور</a></li>
                     <li><a href="#"><i class="icon fa fa-gears"></i> تنظیمات</a></li>
                     <li class="divider"></li>
                     <li><a href="{% url 'logout_user' %}"><i class="icon ion-log-out mt-0"></i> خروج از حساب کاربری</a></li>
                  </ul>
               </li>
            {% endif %}
            </ul>
         </div>
      </div>
   </nav>
   <!-- End nav -->
</header>

templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <meta name="description" content="قالب خبری Magz">
      <meta name="author" content="Kodinger">
      <meta name="keyword" content="قالب خبری، قالب اچ تی ام ال، قالب خبری مگز">
      <!-- Shareable -->
      <meta property="og:title" content="قالب خبری Magz" />
      <meta property="og:type" content="article" />
      <title>{%block title%}{% endblock %}</title>
      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'blog/scripts/bootstrap/bootstrap.min.css'%}">
      <link rel="stylesheet" href="{% static 'blog/css/bootstrap-rtl.min.css'%}">
      <!-- Icons -->
      <link rel="stylesheet" href="{% static 'blog/scripts/ionicons/css/ionicons.min.css'%}">
      <link rel="stylesheet" href="{% static 'blog/scripts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
      <link rel="stylesheet" href="{% static 'blog/scripts/fontawesome-5.0.8/css/fontawesome-all.min.css'%}">
      <!-- Toast -->
      <link rel="stylesheet" href="{% static 'blog/scripts/toast/jquery.toast.min.css'%}">
      <!-- OwlCarousel -->
      <link rel="stylesheet" href="{% static 'blog/scripts/owlcarousel/dist/assets/owl.carousel.min.css'%}">
      <link rel="stylesheet" href="{% static 'blog/scripts/owlcarousel/dist/assets/owl.theme.default.min.css'%}">
      <!-- Magnific Popup -->
      <link rel="stylesheet" href="{% static 'blog/scripts/magnific-popup/dist/magnific-popup.css'%}">
      <link rel="stylesheet" href="{% static 'blog/scripts/sweetalert/dist/sweetalert.css'%}">
      <!-- Custom style -->
      <link rel="stylesheet" href="{% static 'blog/css/style.css'%}">
      <link rel="stylesheet" href="{% static 'blog/css/skins/all.css'%}">
      <link rel="stylesheet" href="{% static 'blog/css/demo.css'%}">
      <style>
         p {
         text-align: justify;
         text-justify: inter-word;
         }
      </style>
      {% block r_header %}
      {% endblock %}
   </head>
   <body class="skin-orange">
      <!-- Start header -->
      {% block header %}
      {% endblock %}
      <!-- End header -->
      <!-- Start main -->
      {% block main%}
      {% endblock %}
      <!-- End main -->
      <!-- Start footer -->
      {% block footer %}
      {% endblock %}
      <!-- End Footer -->
      <!-- JS -->
      <script src="{% static 'blog/js/jquery.js'%}"></script>
      <script src="{% static 'blog/js/jquery.migrate.js'%}"></script>
      <script src="{% static 'blog/scripts/bootstrap/bootstrap.min.js'%}"></script>
      <script>
         var $target_end = $(".best-of-the-week");
      </script>
      <script src="{% static 'blog/scripts/jquery-number/jquery.number.min.js'%}"></script>
      <script src="{% static 'blog/scripts/owlcarousel/dist/owl.carousel.min.js'%}"></script>
      <script src="{% static 'blog/scripts/magnific-popup/dist/jquery.magnific-popup.min.js'%}"></script>
      <script src="{% static 'blog/scripts/easescroll/jquery.easeScroll.js'%}"></script>
      <script src="{% static 'blog/scripts/sweetalert/dist/sweetalert.min.js'%}"></script>
      <script src="{% static 'blog/scripts/toast/jquery.toast.min.js'%}"></script>
      <script src="{% static 'blog/js/demo.js'%}"></script>
      <script src="{% static 'blog/js/e-magz.js'%}"></script>
      {% block r_footer %}
      {% endblock %}
   </body>
</html>

templates/shared/category_base.html
{% extends 'blog/../shared/base.html' %}
{% load static %}
{% load render_partial %}
{% load base_tags %}
{% block header %}
{% render_partial 'header'%}
{% endblock %}
{% block main %}
<section class="category first" style="padding-top: 366px;">
   <div class="container">
      <div class="row">
         <div class="col-md-12 col-lg-8 text-left">
            <div class="row">
               {% block cat_title %}
               {% endblock %}
            </div>
            {% block article %}
            {% endblock %}
            {% block paginator %}
            {% endblock %}
         </div>
      </div>
      <div class="col-md-12 col-lg-4 sidebar">
            <h1 class="aside-title">اخبار جدید</h1>
            <div class="aside-body">
                {% for end_new in end_news1 %}
               <article class="article-fw">
                  <div class="inner">
                     <figure>
                        <a href="{% url 'blog:detail' end_new.slug end_new.id %}">
                        <img src="{{ end_new.image.url }}">
                        </a>
                     </figure>
                     <div class="details">
                        <h1><a href="{% url 'blog:detail' end_new.slug end_new.id %}">{{ end_new.title }}</a>
                        </h1>
                        <p>
                            {{ end_new.descriptions }}
                        </p>
                        <div class="detail">
                           <div class="time">{{ end_new.j_published }}</div>
                            {% for cat in end_new.category.all|slice:"1" %}
                           <div class="category"><a href="{% url 'blog:article-category' cat.slug %}">{{ cat.title }}</a></div>
                                {% endfor %}
                        </div>
                     </div>
                  </div>
               </article>
                {% endfor %}
               <div class="line"></div>
                    {% for end_new in end_news2 %}
               <article class="article-mini">
                  <div class="inner">
                     <figure>
                        <a href="{% url 'blog:detail' end_new.slug end_new.id %}">
                        <img src="{{ end_new.image.url }}">
                        </a>
                     </figure>
                     <div class="padding">
                        <h1><a href="{% url 'blog:detail' end_new.slug end_new.id %}">{{ end_new.title }}</a>
                        </h1>
                        <div class="detail">
                            {% for cat in end_new.category.all|slice:"1" %}
                           <div class="category"><a href="{% url 'blog:article-category' cat.slug %}">{{ cat.title }}</a></div>
                                {% endfor %}
                           <div class="time">{{ end_new.j_published }}</div>
                        </div>
                     </div>
                  </div>
               </article>
                    {% endfor %}

            </div>
         </aside>
         <aside>
            <div class="aside-body">
               <form class="newsletter">
                  <div class="icon">
                     <i class="ion-ios-email-outline"></i>
                     <h1 class="text-center">خبرنامه</h1>
                  </div>
                  <div class="input-group">
                     <input type="email" class="form-control email" placeholder="ایمیل شما">
                     <div class="input-group-btn">
                        <button class="btn btn-primary"><i class="ion-paper-airplane mr-0"></i></button>
                     </div>
                  </div>
                  <p>برای دریافت آخرین اخبار، ایمیل خود را وارد کنید</p>
               </form>
            </div>
         </aside>
      </div>
   </div>
   </div>
</section>
{% endblock main %}
{% block footer %}
{% footer_view %}
{% endblock %}

templates/shared/category_loop.html
<ul class="dropdown-menu">
   {% for cat in cat.children.category_active %}
   {% if cat.children.all  %}
   <li class="dropdown dropdown">
      <a href="{% url 'blog:article-category' cat.slug %}">{{ cat.title }} <i class="fa fa-angle-left"></i></a>
      {% include 'shared/category_loop.html' %}
   </li>
   {% else %}
   <li><a href="{% url 'blog:article-category' cat.slug %}">{{cat.title}}</a></li>
   {% endif %}
   {% endfor %}
</ul>

templates/shared/footer.html
{% load static %}
<footer class="footer">
   <div class="container">
      <div class="row">
         <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="block">
               <h1 class="block-title">درباره ما</h1>
               <div class="block-body">
                  <figure class="foot-logo">
                     <img src="{% static 'blog/images/logo-light.png'%}" class="img-responsive" alt="Logo">
                  </figure>
                  <p class="brand-description">
                   سایت خبری ماگز یک سایت..
                  </p>
                  <a href="{% url 'blog:about-us' %}" class="btn btn-magz white">صفحه درباره ما <i
                     class="ion-ios-arrow-thin-left"></i></a>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="block">
               <h1 class="block-title">
                  برترین برچسب ها
                  <div class="left"><a href="{% url 'blog:hashtag-list' %}">مشاهده همه <i
                     class="ion-ios-arrow-thin-left"></i></a></div>
               </h1>
               <div class="block-body">
                  <ul class="tags">
                      {% for tag in best_tag %}
                     <li><a href="{% url 'blog:hashtag' tag.slug tag.id tag.title %}">{{ tag.title }}</a></li>
                        {% endfor %}
                  </ul>
               </div>
            </div>
            <div class="line"></div>
            <div class="block">
               <h1 class="block-title">خبرنامه</h1>
               <div class="block-body">
                  <p>برای دریافت آخرین اخبار ایمیل خود را وارد کنید</p>
                  <form class="newsletter">
                     <div class="input-group">
                        <div class="input-group-addon">
                           <i class="ion-ios-email-outline"></i>
                        </div>
                        <input type="email" class="form-control email" placeholder="ایمیل شما">
                     </div>
                     <button class="btn btn-primary btn-block white">ثبت ایمیل</button>
                  </form>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="block">
               <h1 class="block-title">آخرین خبر ها</h1>
               <div class="block-body">
                   {% for end_new in end_posts %}
                  <article class="article-mini">
                     <div class="inner">
                        <figure>
                           <a href="{% url 'blog:detail' end_new.slug end_new.id %}">
                           <img src="{{ end_new.image.url }}" alt="Sample Article">
                           </a>
                        </figure>
                        <div class="padding">
                           <h1><a href="{% url 'blog:detail' end_new.slug end_new.id %}">{{ end_new.title }}</a>
                           </h1>
                        </div>
                     </div>
                  </article>
                    {% endfor %}
                  <a href="{% url 'blog:all-article' %}" class="btn btn-magz white btn-block text-center">مشاهده همه <i
                     class="ion-ios-arrow-thin-left"></i></a>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-6 col-xs-12 col-sm-6">
            <div class="block">
               <h1 class="block-title">دنبال کردن</h1>
               <div class="block-body">
                  <p>ما را در شبکه های اجتماعی دنبال کنید</p>
                  <ul class="social trp">
                     <li>
                        <a href="#" class="facebook">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-facebook"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="twitter">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-twitter-outline"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="youtube">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-youtube-outline"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="googleplus">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-googleplus"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="instagram">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-instagram-outline"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="tumblr">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-tumblr"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="dribbble">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-dribbble"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="linkedin">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-linkedin"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="skype">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-skype"></i>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="rss">
                           <svg>
                              <rect width="0" height="0" />
                           </svg>
                           <i class="ion-social-rss"></i>
                        </a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="line"></div>
            <div class="block">
               <div class="block-body no-margin">
                  <ul class="footer-nav-horizontal">
                     <li><a href="{% url 'blog:home' %}">خانه</a></li>
                     <li><a href="{% url 'contact:contact-us' %}">تماس با ما</a></li>
                     <li><a href="{% url 'blog:about-us' %}">در باره ما</a></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-md-12">
            <div class="copyright">
               COPYRIGHT &copy; MAGZ 2020. تمام حقوق محفوظ است.
            </div>
         </div>
      </div>
   </div>
</footer>